version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-it.sh db 5432 &&
             python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://credituser:creditpass@db:5432/creditdb

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-it.sh db 5432 &&
             python manage.py migrate &&
             celery -A app worker --loglevel=info --pool=solo"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://credituser:creditpass@db:5432/creditdb
