version: '3.8'

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A app worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
