# Generated by Django 5.2.1 on 2025-06-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_loans_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='start_date',
            new_name='Date_Approval_loan',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='EMIs_paid_on_time_or_not',
            new_name='EMIs_paid_on_time',
        ),
    ]
