# Generated by Django 5.2.1 on 2025-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_start_date_loans_date_approval_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='current_debt',
            field=models.FloatField(default=0.0),
        ),
    ]
