# Generated by Django 5.2.1 on 2025-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customers_current_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.customers'),
        ),
    ]
